-- MySQL Script generated by MySQL Workbench
-- Sat Sep 14 15:03:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sustentech` DEFAULT CHARACTER SET utf8 ;
USE `bd_sustentech` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sustentech`.`tb_vendedores` (
  `cd_cliente` INT NOT NULL AUTO_INCREMENT,
  `nm_cliente` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nm_endereco` VARCHAR(45) NOT NULL,
  `nr_endereco` CHAR(10) NOT NULL,
  `nr_cep` CHAR(8) NOT NULL,
  `sg_estado` VARCHAR(2) NOT NULL,
  `nr_telefone` CHAR(9) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sustentech`.`tb_empresa` (
  `cd_empresa` INT NOT NULL AUTO_INCREMENT,
  `nm_empresa` VARCHAR(255) NOT NULL,
  `cpnj_empresa` CHAR(14) NOT NULL,
  `nm_endereco` VARCHAR(45) NOT NULL,
  `nr_endereco` CHAR(4) NOT NULL,
  `nr_cep` CHAR(8) NOT NULL,
  `nr_telefone` CHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nm_responsavel` VARCHAR(45) NOT NULL,
  `cargo_responsavel` VARCHAR(45) NOT NULL,
  `email_responsavel` VARCHAR(45) NOT NULL,
  `atividade_economica` CHAR(7) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ds_servico` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cd_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_Cooperativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sustentech`.`tb_Cooperativa` (
  `cd_corporativa` INT NOT NULL AUTO_INCREMENT,
  `nm_corporativa` VARCHAR(45) NOT NULL,
  `nr_cnpj` CHAR(14) NOT NULL,
  `nr_telefone` CHAR(9) NOT NULL,
  `email` VARCHAR(45) NULL,
  `nm_endereco` VARCHAR(45) NOT NULL,
  `nr_endereco` VARCHAR(45) NOT NULL,
  `hr_funcionamento` DATETIME NOT NULL,
  `nr_cep` CHAR(8) NOT NULL,
  `ds_itensRecebidos` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_corporativa`))
ENGINE = InnoDB;


use bd_sustentech;
alter table tb_empresa modify senha varchar (255);



-- -----------------------------------------------------
-- Table `mydb`.`tb_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sustentech`.`tb_tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Smartphone` VARCHAR(10) NOT NULL,
  `Notebooks` VARCHAR(9) NOT NULL,
  `Tvs e monitores` VARCHAR(13) NOT NULL,
  `Desktops` VARCHAR(8) NOT NULL,
  `Fones e headsets` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Sustentech`.`tb_produto` (
  `cd_produto` INT NOT NULL AUTO_INCREMENT,
  `nm_produto` VARCHAR(45) NOT NULL,
  `nm_marca` VARCHAR(45) NOT NULL,
  `dt_compra` DATE NOT NULL,
  `marca_componentes` VARCHAR(45) NOT NULL,
  `modelo_produto` VARCHAR(45) NOT NULL,
  `condicao_produto` VARCHAR(45) NOT NULL,
  `ds_produto` VARCHAR(45) NOT NULL,
  `vl_produto` VARCHAR(45) NOT NULL,
  `tb_vendedores_cd_cliente` INT NOT NULL,
  `tb_empresa_cd_empresa` INT NOT NULL,
  `tb_Creciclagem_cd_corporativa` INT NOT NULL,
  `tb_tags_id` INT NOT NULL,
  PRIMARY KEY (`cd_produto`),
  INDEX `fk_tb_produto_tb_vendedores_idx` (`tb_vendedores_cd_cliente` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_empresa1_idx` (`tb_empresa_cd_empresa` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_Creciclagem1_idx` (`tb_Creciclagem_cd_corporativa` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_tags1_idx` (`tb_tags_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_vendedores`
    FOREIGN KEY (`tb_vendedores_cd_cliente`)
    REFERENCES `bd_sustentech`.`tb_vendedores` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_empresa1`
    FOREIGN KEY (`tb_empresa_cd_empresa`)
    REFERENCES `bd_sustentech`.`tb_empresa` (`cd_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_Creciclagem1`
    FOREIGN KEY (`tb_Creciclagem_cd_corporativa`)
    REFERENCES `bd_sustentech`.`tb_Cooperativa` (`cd_corporativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_tags1`
    FOREIGN KEY (`tb_tags_id`)
    REFERENCES `bd_sustentech`.`tb_tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use bd_sustentech;
ALTER TABLE tb_produto
DROP FOREIGN KEY fk_tb_produto_tb_Creciclagem1;
ALTER TABLE tb_produto
DROP COLUMN tb_Creciclagem_cd_corporativa;

drop table tb_cooperativa;

alter table tb_tags
drop column Smartphone ,
drop column Notebooks ;
 
ALTER TABLE tb_produto
DROP FOREIGN KEY fk_tb_produto_tb_tags1;
ALTER TABLE tb_produto
DROP COLUMN tb_tags_id;

USE bd_sustentech;

CREATE TABLE tb_tags (
    id_tag INT AUTO_INCREMENT PRIMARY KEY,
    nm_tag VARCHAR(50) NOT NULL
);

drop table tb_cooperativa;

use bs_sustentech;
alter table tb_vendedores;
ALTER TABLE tb_vendedores RENAME TO tb_usuarios;
ALTER TABLE tb_vendedores
MODIFY COLUMN nr_telefone char(11);


ALTER TABLE `bd_sustentech`.`tb_produto`
DROP FOREIGN KEY `fk_tb_produto_tb_vendedores`;

-- Adicionar as foreign keys com o nome atualizado
ALTER TABLE `bd_Sustentech`.`tb_produto`
ADD CONSTRAINT `fk_tb_produto_tb_usuarios`
  FOREIGN KEY (`tb_usuarios_cd_cliente`)
  REFERENCES `bd_sustentech`.`tb_usuarios` (`cd_cliente`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  -- Renomeie a coluna para refletir o novo nome
ALTER TABLE `bd_Sustentech`.`tb_produto`
  CHANGE COLUMN `tb_vendedores_cd_cliente` `tb_usuarios_cd_cliente` INT NULL;

-- Agora adicione a nova constraint com o nome atualizado
ALTER TABLE `bd_Sustentech`.`tb_produto`
  ADD CONSTRAINT `fk_tb_produto_tb_usuarios`
  FOREIGN KEY (`tb_usuarios_cd_cliente`)
  REFERENCES `bd_sustentech`.`tb_usuarios` (`cd_cliente`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  use bd_sustentech;
  CREATE TABLE tb_redefinicao_senha (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    expira_em DATETIME NOT NULL
);
use bd_sustentech;
drop table tb_redefinicao_senha;

alter table tb_usuarios 
ADD COLUMN reset_token VARCHAR(100);








